import Head from "next/head";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Card005 from "@/components/cards/Card005";

export default function Post() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <section className="max-w-7xl mx-auto pt-20 pb-10 px-4 md:px-0">
          <section className="grid md:grid-cols-6  pt-20">
            <div className="md:col-span-4 order-2 md:order-1">
              <Card005 />
            </div>
            <div className="md:col-span-2 order-1 md:order-2 ml-20 hidden md:block">
              <h4 className="text-base font-semibold uppercase text-gray-600">
                Categories
              </h4>
              <div className="grid grid-cols-3 gap-2 pt-5">
                <div className="px-3 py-2 bg-gray-100 text-gray-700 text-xs text-center tracking-wide">
                  Entertainment
                </div>
                <div className="px-3 py-2 bg-gray-100 text-gray-700 text-xs text-center tracking-wide">
                  Games
                </div>
                <div className="px-3 py-2 bg-gray-100 text-gray-700 text-xs text-center tracking-wide">
                  News
                </div>
                <div className="px-3 py-2 bg-gray-100 text-gray-700 text-xs text-center tracking-wide">
                  Uncategorized
                </div>
              </div>
            </div>
          </section>
        </section>
        <Footer />
      </main>
    </>
  );
}
