import Head from "next/head";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
import Card003 from "@/components/cards/Card003";
import SearchInput from "@/components/SearchInput";
export default function Blog() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <section className="max-w-7xl mx-auto pt-20 pb-10 px-4 md:px-0">
          <section className="grid md:grid-cols-6 gap-10 pt-20">
            <div className="md:col-span-4 order-2 md:order-1">
              <Card003 />
              <Card003 />
              <Card003 />
              <Card003 />
            </div>
            <div className="md:col-span-2 order-1 md:order-2">
              <SearchInput />
            </div>
          </section>
        </section>
      </main>
      <Footer />
    </>
  );
}
