import Head from "next/head";
import NavBar from "@/components/NavBar";
import Footer from "@/components/Footer";
export default function Investors() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <NavBar />
        <Footer />
      </main>
    </>
  );
}
